---
- name: Start sandbox instances
  hosts: localhost
  gather_facts: false
  vars:
    instance_ids:
      - 'i-0afa2f2543f475598'
      
    region: ap-south-1
  tasks:
    - name: Start the sandbox instances
      ec2:
        instance_ids: '{{ i-0afa2f2543f475598 }}'
        region: '{{ ap-south-1 }}'
        state: running
        wait: True
        vpc_subnet_id: subnet-09d57466a48d2af26
        assign_public_ip: yes
  roles:
    - do_neat_stuff
    - do_more_neat_stuff
