- name: stop instance
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
   instance_ids:
     - i-0afa2f2543f475598 
   region: ap-south-1
  tasks:
    - name: start the instances
      ec2_instance:
       instance_ids: '{{ instance_ids}}'
       region: '{{ region }}'
       state: stopped
       wait: true
       vpc_subnet_id: subnet-09d57466a48d2af26
